import { Roboto } from "next/font/google";
import Header from "../components/shared/Header.jsx";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata = {
  title: "Zahid Hasan Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
